#! /nix/store/00zrahbb32nzawrmv9sjxn36h7qk9vrs-bash-5.2p37/bin/bash -e
export NVIM_SYSTEM_RPLUGIN_MANIFEST='/nix/store/pbs6cfqxfh8jsr627ykpx6n5vwfjz3pf-neovim-nightly/rplugin.vim'
export GEM_HOME='/nix/store/6mp5806z3sq8ys0zifrhlaih4afikc9x-neovim-ruby-env/lib/ruby/gems/3.3.0'
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/6mp5806z3sq8ys0zifrhlaih4afikc9x-neovim-ruby-env/bin'':'* ]]; then
    PATH=$PATH'/nix/store/6mp5806z3sq8ys0zifrhlaih4afikc9x-neovim-ruby-env/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/pjr8jcds298brhwy1d3rmym9vayxhbfs-nodejs-22.16.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/pjr8jcds298brhwy1d3rmym9vayxhbfs-nodejs-22.16.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/n4jxx1f58x3gsr9k9msm3q88kqjkxk4m-llm-ls-0.5.3/bin'':'* ]]; then
    PATH=$PATH'/nix/store/n4jxx1f58x3gsr9k9msm3q88kqjkxk4m-llm-ls-0.5.3/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/7xllvpjj8a7rv1mq7mxzj657q520vl26-typescript-language-server-4.3.3/bin'':'* ]]; then
    PATH=$PATH'/nix/store/7xllvpjj8a7rv1mq7mxzj657q520vl26-typescript-language-server-4.3.3/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/59515k9fy7cigbjxkjc5biiipayfsmdy-fzf-0.63.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/59515k9fy7cigbjxkjc5biiipayfsmdy-fzf-0.63.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/2mv5vairslzm6f38655km888m55hqcfk-bash-language-server-5.6.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/2mv5vairslzm6f38655km888m55hqcfk-bash-language-server-5.6.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/mq2i9br9h890bnahlds9jnff1jf6xjpb-python3.13-black-25.1.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/mq2i9br9h890bnahlds9jnff1jf6xjpb-python3.13-black-25.1.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/c4dr8m59cry5ms7ixx5wb0hnfglb5fhq-editorconfig-checker-3.3.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/c4dr8m59cry5ms7ixx5wb0hnfglb5fhq-editorconfig-checker-3.3.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/cxp7hm4z67b1p5gz28p8qb5gnkh5g7ki-fswatch-1.18.3/bin'':'* ]]; then
    PATH=$PATH'/nix/store/cxp7hm4z67b1p5gz28p8qb5gnkh5g7ki-fswatch-1.18.3/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/mdn9hnvf0qmxywbrpbywmxww2adxdn5v-go-1.24.4/bin'':'* ]]; then
    PATH=$PATH'/nix/store/mdn9hnvf0qmxywbrpbywmxww2adxdn5v-go-1.24.4/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/lnx8a1q9j4xl7f28ww93crqhgzm5byjx-luajit2.1-luacheck-1.2.0-1/bin'':'* ]]; then
    PATH=$PATH'/nix/store/lnx8a1q9j4xl7f28ww93crqhgzm5byjx-luajit2.1-luacheck-1.2.0-1/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/5vb1wdxy16fjbmdchn61wlwnq15jr2ww-luaformatter-1.3.6/bin'':'* ]]; then
    PATH=$PATH'/nix/store/5vb1wdxy16fjbmdchn61wlwnq15jr2ww-luaformatter-1.3.6/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/j7k1j3zq3lw8fwc0f446zydp1x8zjcaj-hasktags-0.73.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/j7k1j3zq3lw8fwc0f446zydp1x8zjcaj-hasktags-0.73.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/k3hxxyvmil8q1pan2v25f5ff3sc6wanl-fast-tags-2.0.3/bin'':'* ]]; then
    PATH=$PATH'/nix/store/k3hxxyvmil8q1pan2v25f5ff3sc6wanl-fast-tags-2.0.3/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/jn0xyf3bqc0d4sbfv47cabpp29i6nxlz-manix-0.8.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/jn0xyf3bqc0d4sbfv47cabpp29i6nxlz-manix-0.8.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/vbk9blw37mhp7syzkhy9y5jwdczgsfxp-vscode-langservers-extracted-4.10.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/vbk9blw37mhp7syzkhy9y5jwdczgsfxp-vscode-langservers-extracted-4.10.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/2p53xg7kmwpvwki9b7mi0w749gr0gpdy-dockerfile-language-server-nodejs-0.11.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/2p53xg7kmwpvwki9b7mi0w749gr0gpdy-dockerfile-language-server-nodejs-0.11.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/083hrk7nck7vp1z00qk3iyaxcmxcvpl2-nil-2025-06-13/bin'':'* ]]; then
    PATH=$PATH'/nix/store/083hrk7nck7vp1z00qk3iyaxcmxcvpl2-nil-2025-06-13/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/0zrd8dl8qv05hf3928a3655320s33v50-nixd-2.6.4/bin'':'* ]]; then
    PATH=$PATH'/nix/store/0zrd8dl8qv05hf3928a3655320s33v50-nixd-2.6.4/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/j9a59r3plh1ywzphwyvpfv57vki42ymn-rust-analyzer-2025-06-16/bin'':'* ]]; then
    PATH=$PATH'/nix/store/j9a59r3plh1ywzphwyvpfv57vki42ymn-rust-analyzer-2025-06-16/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/6lp66063vh1gsva6ypgy04wdjkcy67nq-shellcheck-0.10.0-bin/bin'':'* ]]; then
    PATH=$PATH'/nix/store/6lp66063vh1gsva6ypgy04wdjkcy67nq-shellcheck-0.10.0-bin/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/j3402mwz5i1crm5b576774spwmqj4r6g-lua-language-server-3.14.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/j3402mwz5i1crm5b576774spwmqj4r6g-lua-language-server-3.14.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/26pxyvnsgh0psak2xd8jm9884xdi40z3-gopls-0.19.1/bin'':'* ]]; then
    PATH=$PATH'/nix/store/26pxyvnsgh0psak2xd8jm9884xdi40z3-gopls-0.19.1/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/43jgkxxmwscw0z04msfm2s3bgqdlxkgq-marksman-2024-12-18/bin'':'* ]]; then
    PATH=$PATH'/nix/store/43jgkxxmwscw0z04msfm2s3bgqdlxkgq-marksman-2024-12-18/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/yz9cnfqd6ip5f91gk91vd9bwa43j31w8-nixfmt-unstable-2025-04-04/bin'':'* ]]; then
    PATH=$PATH'/nix/store/yz9cnfqd6ip5f91gk91vd9bwa43j31w8-nixfmt-unstable-2025-04-04/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/xhcmdcv5pslksh0d9ibxvgjcvz1862ln-prettier-3.5.3/bin'':'* ]]; then
    PATH=$PATH'/nix/store/xhcmdcv5pslksh0d9ibxvgjcvz1862ln-prettier-3.5.3/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/mdzm1l0rnpwp8ha0mbxll0db4r2p0xj3-python3.13-flake8-7.2.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/mdzm1l0rnpwp8ha0mbxll0db4r2p0xj3-python3.13-flake8-7.2.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/17cxjsyiqrkinnq8gqabq75al8zaw6y0-pyright-1.1.400/bin'':'* ]]; then
    PATH=$PATH'/nix/store/17cxjsyiqrkinnq8gqabq75al8zaw6y0-pyright-1.1.400/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/0lqgc07nvj6xjnq7ph7ai70q0pfgdpa4-yaml-language-server-1.18.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/0lqgc07nvj6xjnq7ph7ai70q0pfgdpa4-yaml-language-server-1.18.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/61yzr13fxfhg397ilg62klaxqfnpggi6-python3.13-yamllint-1.37.1/bin'':'* ]]; then
    PATH=$PATH'/nix/store/61yzr13fxfhg397ilg62klaxqfnpggi6-python3.13-yamllint-1.37.1/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/j3yy5an3mprkj7adik62g97j88g17spd-yamlfmt-0.17.1/bin'':'* ]]; then
    PATH=$PATH'/nix/store/j3yy5an3mprkj7adik62g97j88g17spd-yamlfmt-0.17.1/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/n4jxx1f58x3gsr9k9msm3q88kqjkxk4m-llm-ls-0.5.3/bin'':'* ]]; then
    PATH=$PATH'/nix/store/n4jxx1f58x3gsr9k9msm3q88kqjkxk4m-llm-ls-0.5.3/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/60pzn68j5hc54zj806jx7q8ac33d18k4-stylua-2.1.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/60pzn68j5hc54zj806jx7q8ac33d18k4-stylua-2.1.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/5imbpm6czrv3zq4j9k7f3hs10gd6kls3-gitlab-ci-ls-1.1.1/bin'':'* ]]; then
    PATH=$PATH'/nix/store/5imbpm6czrv3zq4j9k7f3hs10gd6kls3-gitlab-ci-ls-1.1.1/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/049j68vig3ipggrp2givd0cbvmq00334-mcp-hub-3.7.0/bin'':'* ]]; then
    PATH=$PATH'/nix/store/049j68vig3ipggrp2givd0cbvmq00334-mcp-hub-3.7.0/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
PATH=${PATH:+':'$PATH':'}
if [[ $PATH != *':''/nix/store/6lp66063vh1gsva6ypgy04wdjkcy67nq-shellcheck-0.10.0-bin/bin'':'* ]]; then
    PATH=$PATH'/nix/store/6lp66063vh1gsva6ypgy04wdjkcy67nq-shellcheck-0.10.0-bin/bin'
fi
PATH=${PATH#':'}
PATH=${PATH%':'}
export PATH
LUA_CPATH=${LUA_CPATH:+';'$LUA_CPATH';'}
if [[ $LUA_CPATH != *';''/nix/store/nxhvrymvp33q6v8ab2800fcwvvbc5pab-luajit2.1-sqlite-v1.2.2-0/lib/lua/5.1/?.so'';'* ]]; then
    LUA_CPATH=$LUA_CPATH'/nix/store/nxhvrymvp33q6v8ab2800fcwvvbc5pab-luajit2.1-sqlite-v1.2.2-0/lib/lua/5.1/?.so'
fi
LUA_CPATH=${LUA_CPATH#';'}
LUA_CPATH=${LUA_CPATH%';'}
export LUA_CPATH
LUA_CPATH=${LUA_CPATH:+';'$LUA_CPATH';'}
if [[ $LUA_CPATH != *';''/nix/store/sdib83aavn0vanmwws0q1kkdblxghah3-luajit2.1-lsqlite3-0.9.6-1/lib/lua/5.1/?.so'';'* ]]; then
    LUA_CPATH=$LUA_CPATH'/nix/store/sdib83aavn0vanmwws0q1kkdblxghah3-luajit2.1-lsqlite3-0.9.6-1/lib/lua/5.1/?.so'
fi
LUA_CPATH=${LUA_CPATH#';'}
LUA_CPATH=${LUA_CPATH%';'}
export LUA_CPATH
LUA_CPATH=${LUA_CPATH:+';'$LUA_CPATH';'}
if [[ $LUA_CPATH != *';''/nix/store/phxn7yzscwbd4qrffgfvgravnpxkg1sa-luajit2.1-lual-1.0.15-1/lib/lua/5.1/?.so'';'* ]]; then
    LUA_CPATH=$LUA_CPATH'/nix/store/phxn7yzscwbd4qrffgfvgravnpxkg1sa-luajit2.1-lual-1.0.15-1/lib/lua/5.1/?.so'
fi
LUA_CPATH=${LUA_CPATH#';'}
LUA_CPATH=${LUA_CPATH%';'}
export LUA_CPATH
LUA_CPATH=${LUA_CPATH:+';'$LUA_CPATH';'}
if [[ $LUA_CPATH != *';''/nix/store/2ab3fahdxxrll8sm9ys3vc62whzpcmq2-luajit2.1-utf8-1.3-0/lib/lua/5.1/?.so'';'* ]]; then
    LUA_CPATH=$LUA_CPATH'/nix/store/2ab3fahdxxrll8sm9ys3vc62whzpcmq2-luajit2.1-utf8-1.3-0/lib/lua/5.1/?.so'
fi
LUA_CPATH=${LUA_CPATH#';'}
LUA_CPATH=${LUA_CPATH%';'}
export LUA_CPATH
LUA_CPATH=${LUA_CPATH:+';'$LUA_CPATH';'}
if [[ $LUA_CPATH != *';''/nix/store/9f35dshqamx5d90sklmz78rpbjdnpz82-luajit2.1-nvim-nio-1.10.1-1/lib/lua/5.1/?.so'';'* ]]; then
    LUA_CPATH=$LUA_CPATH'/nix/store/9f35dshqamx5d90sklmz78rpbjdnpz82-luajit2.1-nvim-nio-1.10.1-1/lib/lua/5.1/?.so'
fi
LUA_CPATH=${LUA_CPATH#';'}
LUA_CPATH=${LUA_CPATH%';'}
export LUA_CPATH
LUA_CPATH=${LUA_CPATH:+';'$LUA_CPATH';'}
if [[ $LUA_CPATH != *';''/nix/store/vd7snnxznala5pwq8dhw26lnyy91wjzh-luajit2.1-fzy-1.0.3-1/lib/lua/5.1/?.so'';'* ]]; then
    LUA_CPATH=$LUA_CPATH'/nix/store/vd7snnxznala5pwq8dhw26lnyy91wjzh-luajit2.1-fzy-1.0.3-1/lib/lua/5.1/?.so'
fi
LUA_CPATH=${LUA_CPATH#';'}
LUA_CPATH=${LUA_CPATH%';'}
export LUA_CPATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
if [[ $LUA_PATH != *';''/nix/store/nxhvrymvp33q6v8ab2800fcwvvbc5pab-luajit2.1-sqlite-v1.2.2-0/share/lua/5.1/?.lua'';'* ]]; then
    LUA_PATH=$LUA_PATH'/nix/store/nxhvrymvp33q6v8ab2800fcwvvbc5pab-luajit2.1-sqlite-v1.2.2-0/share/lua/5.1/?.lua'
fi
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
if [[ $LUA_PATH != *';''/nix/store/nxhvrymvp33q6v8ab2800fcwvvbc5pab-luajit2.1-sqlite-v1.2.2-0/share/lua/5.1/?/init.lua'';'* ]]; then
    LUA_PATH=$LUA_PATH'/nix/store/nxhvrymvp33q6v8ab2800fcwvvbc5pab-luajit2.1-sqlite-v1.2.2-0/share/lua/5.1/?/init.lua'
fi
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
if [[ $LUA_PATH != *';''/nix/store/sdib83aavn0vanmwws0q1kkdblxghah3-luajit2.1-lsqlite3-0.9.6-1/share/lua/5.1/?.lua'';'* ]]; then
    LUA_PATH=$LUA_PATH'/nix/store/sdib83aavn0vanmwws0q1kkdblxghah3-luajit2.1-lsqlite3-0.9.6-1/share/lua/5.1/?.lua'
fi
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
if [[ $LUA_PATH != *';''/nix/store/sdib83aavn0vanmwws0q1kkdblxghah3-luajit2.1-lsqlite3-0.9.6-1/share/lua/5.1/?/init.lua'';'* ]]; then
    LUA_PATH=$LUA_PATH'/nix/store/sdib83aavn0vanmwws0q1kkdblxghah3-luajit2.1-lsqlite3-0.9.6-1/share/lua/5.1/?/init.lua'
fi
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
if [[ $LUA_PATH != *';''/nix/store/phxn7yzscwbd4qrffgfvgravnpxkg1sa-luajit2.1-lual-1.0.15-1/share/lua/5.1/?.lua'';'* ]]; then
    LUA_PATH=$LUA_PATH'/nix/store/phxn7yzscwbd4qrffgfvgravnpxkg1sa-luajit2.1-lual-1.0.15-1/share/lua/5.1/?.lua'
fi
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
if [[ $LUA_PATH != *';''/nix/store/phxn7yzscwbd4qrffgfvgravnpxkg1sa-luajit2.1-lual-1.0.15-1/share/lua/5.1/?/init.lua'';'* ]]; then
    LUA_PATH=$LUA_PATH'/nix/store/phxn7yzscwbd4qrffgfvgravnpxkg1sa-luajit2.1-lual-1.0.15-1/share/lua/5.1/?/init.lua'
fi
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
if [[ $LUA_PATH != *';''/nix/store/2ab3fahdxxrll8sm9ys3vc62whzpcmq2-luajit2.1-utf8-1.3-0/share/lua/5.1/?.lua'';'* ]]; then
    LUA_PATH=$LUA_PATH'/nix/store/2ab3fahdxxrll8sm9ys3vc62whzpcmq2-luajit2.1-utf8-1.3-0/share/lua/5.1/?.lua'
fi
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
if [[ $LUA_PATH != *';''/nix/store/2ab3fahdxxrll8sm9ys3vc62whzpcmq2-luajit2.1-utf8-1.3-0/share/lua/5.1/?/init.lua'';'* ]]; then
    LUA_PATH=$LUA_PATH'/nix/store/2ab3fahdxxrll8sm9ys3vc62whzpcmq2-luajit2.1-utf8-1.3-0/share/lua/5.1/?/init.lua'
fi
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
if [[ $LUA_PATH != *';''/nix/store/9f35dshqamx5d90sklmz78rpbjdnpz82-luajit2.1-nvim-nio-1.10.1-1/share/lua/5.1/?.lua'';'* ]]; then
    LUA_PATH=$LUA_PATH'/nix/store/9f35dshqamx5d90sklmz78rpbjdnpz82-luajit2.1-nvim-nio-1.10.1-1/share/lua/5.1/?.lua'
fi
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
if [[ $LUA_PATH != *';''/nix/store/9f35dshqamx5d90sklmz78rpbjdnpz82-luajit2.1-nvim-nio-1.10.1-1/share/lua/5.1/?/init.lua'';'* ]]; then
    LUA_PATH=$LUA_PATH'/nix/store/9f35dshqamx5d90sklmz78rpbjdnpz82-luajit2.1-nvim-nio-1.10.1-1/share/lua/5.1/?/init.lua'
fi
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
if [[ $LUA_PATH != *';''/nix/store/vd7snnxznala5pwq8dhw26lnyy91wjzh-luajit2.1-fzy-1.0.3-1/share/lua/5.1/?.lua'';'* ]]; then
    LUA_PATH=$LUA_PATH'/nix/store/vd7snnxznala5pwq8dhw26lnyy91wjzh-luajit2.1-fzy-1.0.3-1/share/lua/5.1/?.lua'
fi
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
if [[ $LUA_PATH != *';''/nix/store/vd7snnxznala5pwq8dhw26lnyy91wjzh-luajit2.1-fzy-1.0.3-1/share/lua/5.1/?/init.lua'';'* ]]; then
    LUA_PATH=$LUA_PATH'/nix/store/vd7snnxznala5pwq8dhw26lnyy91wjzh-luajit2.1-fzy-1.0.3-1/share/lua/5.1/?/init.lua'
fi
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/l0lag83123yzm1jpgi26vgq4rliv9988-lua5.1-luarocks-build-treesitter-parser-6.0.1-1/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/l0lag83123yzm1jpgi26vgq4rliv9988-lua5.1-luarocks-build-treesitter-parser-6.0.1-1/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/qif59pxb4h4z5yxw07xaaawxbgyqlbk0-lua5.1-fidget.nvim-1.6.0-1/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/qif59pxb4h4z5yxw07xaaawxbgyqlbk0-lua5.1-fidget.nvim-1.6.0-1/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/0v042m5ihs2z04qb1pzz7z2vid09vjb9-lua5.1-xml2lua-1.6-2/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/0v042m5ihs2z04qb1pzz7z2vid09vjb9-lua5.1-xml2lua-1.6-2/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/rmsgkbbvj6bijdg1fjmk4jc767r4wxzv-lua5.1-mimetypes-1.1.0-2/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/rmsgkbbvj6bijdg1fjmk4jc767r4wxzv-lua5.1-mimetypes-1.1.0-2/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/473m4fzsrr5f654mxz3jmyql68bsylab-lua5.1-nvim-nio-1.10.1-1/share/lua/5.1/?/init.lua'';'/';'}
LUA_PATH='/nix/store/473m4fzsrr5f654mxz3jmyql68bsylab-lua5.1-nvim-nio-1.10.1-1/share/lua/5.1/?/init.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/473m4fzsrr5f654mxz3jmyql68bsylab-lua5.1-nvim-nio-1.10.1-1/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/473m4fzsrr5f654mxz3jmyql68bsylab-lua5.1-nvim-nio-1.10.1-1/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/hkdpk1m9n714852rkxxqnvvczmghlx51-luajit2.1-rtp.nvim-1.2.0-1/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/hkdpk1m9n714852rkxxqnvvczmghlx51-luajit2.1-rtp.nvim-1.2.0-1/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/9f35dshqamx5d90sklmz78rpbjdnpz82-luajit2.1-nvim-nio-1.10.1-1/share/lua/5.1/?/init.lua'';'/';'}
LUA_PATH='/nix/store/9f35dshqamx5d90sklmz78rpbjdnpz82-luajit2.1-nvim-nio-1.10.1-1/share/lua/5.1/?/init.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/9f35dshqamx5d90sklmz78rpbjdnpz82-luajit2.1-nvim-nio-1.10.1-1/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/9f35dshqamx5d90sklmz78rpbjdnpz82-luajit2.1-nvim-nio-1.10.1-1/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/89vm7hrdp1jz5i3riqfd7kbndcqn51n3-luajit2.1-luarocks-3.11.1-1/share/lua/5.1/?/init.lua'';'/';'}
LUA_PATH='/nix/store/89vm7hrdp1jz5i3riqfd7kbndcqn51n3-luajit2.1-luarocks-3.11.1-1/share/lua/5.1/?/init.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/89vm7hrdp1jz5i3riqfd7kbndcqn51n3-luajit2.1-luarocks-3.11.1-1/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/89vm7hrdp1jz5i3riqfd7kbndcqn51n3-luajit2.1-luarocks-3.11.1-1/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/vd7snnxznala5pwq8dhw26lnyy91wjzh-luajit2.1-fzy-1.0.3-1/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/vd7snnxznala5pwq8dhw26lnyy91wjzh-luajit2.1-fzy-1.0.3-1/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/fx44ax0k1yfa6a61bhanp3lzg42c5f51-luajit2.1-fidget.nvim-1.6.0-1/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/fx44ax0k1yfa6a61bhanp3lzg42c5f51-luajit2.1-fidget.nvim-1.6.0-1/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/72k441ysacp8kacqyqn0kxrsrp6rzzsa-luajit2.1-say-1.4.1-3/share/lua/5.1/?/init.lua'';'/';'}
LUA_PATH='/nix/store/72k441ysacp8kacqyqn0kxrsrp6rzzsa-luajit2.1-say-1.4.1-3/share/lua/5.1/?/init.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/72k441ysacp8kacqyqn0kxrsrp6rzzsa-luajit2.1-say-1.4.1-3/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/72k441ysacp8kacqyqn0kxrsrp6rzzsa-luajit2.1-say-1.4.1-3/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/q500ld4hwkzj0kgd3zxkb04vnxf6a8hp-luajit2.1-luassert-1.9.0-1/share/lua/5.1/?/init.lua'';'/';'}
LUA_PATH='/nix/store/q500ld4hwkzj0kgd3zxkb04vnxf6a8hp-luajit2.1-luassert-1.9.0-1/share/lua/5.1/?/init.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/q500ld4hwkzj0kgd3zxkb04vnxf6a8hp-luajit2.1-luassert-1.9.0-1/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/q500ld4hwkzj0kgd3zxkb04vnxf6a8hp-luajit2.1-luassert-1.9.0-1/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/7w43i4f2aas1faqbqww9wi3s9qmh05ml-luajit-2.1.1741730670/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/7w43i4f2aas1faqbqww9wi3s9qmh05ml-luajit-2.1.1741730670/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_PATH=${LUA_PATH:+';'$LUA_PATH';'}
LUA_PATH=${LUA_PATH/';''/nix/store/sra66lkmmh33ijcjvpr6lvf93xfhpi3j-luajit2.1-nvim-web-devicons-0.100-1/share/lua/5.1/?.lua'';'/';'}
LUA_PATH='/nix/store/sra66lkmmh33ijcjvpr6lvf93xfhpi3j-luajit2.1-nvim-web-devicons-0.100-1/share/lua/5.1/?.lua'$LUA_PATH
LUA_PATH=${LUA_PATH#';'}
LUA_PATH=${LUA_PATH%';'}
export LUA_PATH
LUA_CPATH=${LUA_CPATH:+';'$LUA_CPATH';'}
LUA_CPATH=${LUA_CPATH/';''/nix/store/462vlc7ha87si6jgn8gk2pffv2p4l50i-lua5.1-luafilesystem-1.8.0-1/lib/lua/5.1/?.so'';'/';'}
LUA_CPATH='/nix/store/462vlc7ha87si6jgn8gk2pffv2p4l50i-lua5.1-luafilesystem-1.8.0-1/lib/lua/5.1/?.so'$LUA_CPATH
LUA_CPATH=${LUA_CPATH#';'}
LUA_CPATH=${LUA_CPATH%';'}
export LUA_CPATH
LUA_CPATH=${LUA_CPATH:+';'$LUA_CPATH';'}
LUA_CPATH=${LUA_CPATH/';''/nix/store/lc3dgzjh0lx8rxd7vg6yy7fwg78aiwm8-lua5.1-tree-sitter-http-0.0.35-1/lib/lua/5.1/?.so'';'/';'}
LUA_CPATH='/nix/store/lc3dgzjh0lx8rxd7vg6yy7fwg78aiwm8-lua5.1-tree-sitter-http-0.0.35-1/lib/lua/5.1/?.so'$LUA_CPATH
LUA_CPATH=${LUA_CPATH#';'}
LUA_CPATH=${LUA_CPATH%';'}
export LUA_CPATH
LUA_CPATH=${LUA_CPATH:+';'$LUA_CPATH';'}
LUA_CPATH=${LUA_CPATH/';''/nix/store/fh9iswgld7kldbd2fpc6q5y2d349b3k7-luajit2.1-toml-edit-0.6.1-1/lib/lua/5.1/?.so'';'/';'}
LUA_CPATH='/nix/store/fh9iswgld7kldbd2fpc6q5y2d349b3k7-luajit2.1-toml-edit-0.6.1-1/lib/lua/5.1/?.so'$LUA_CPATH
LUA_CPATH=${LUA_CPATH#';'}
LUA_CPATH=${LUA_CPATH%';'}
export LUA_CPATH
LUA_CPATH=${LUA_CPATH:+';'$LUA_CPATH';'}
LUA_CPATH=${LUA_CPATH/';''/nix/store/vd7snnxznala5pwq8dhw26lnyy91wjzh-luajit2.1-fzy-1.0.3-1/lib/lua/5.1/?.so'';'/';'}
LUA_CPATH='/nix/store/vd7snnxznala5pwq8dhw26lnyy91wjzh-luajit2.1-fzy-1.0.3-1/lib/lua/5.1/?.so'$LUA_CPATH
LUA_CPATH=${LUA_CPATH#';'}
LUA_CPATH=${LUA_CPATH%';'}
export LUA_CPATH
lua
