--[[
Returns values based on an sqlite db generated by https://github.com/odrevet/edict_database
The db itself is generated via edict
--]]

-- (or sqlite3 = require('lsqlite3complete')) 
local sqlite3 = require('lsqlite3')
local config = require('jap-nvim.config')

local M = {}

function M.kanji_sql(kanji)
    return [[
SELECT character.*, 
GROUP_CONCAT(DISTINCT character_radical.id_radical) as radicals, 
GROUP_CONCAT(DISTINCT on_yomi.reading) AS on_reading, 
GROUP_CONCAT(DISTINCT kun_yomi.reading) AS kun_reading, 
GROUP_CONCAT(DISTINCT meaning.content) AS meanings 
FROM character 
LEFT JOIN character_radical ON character.id = character_radical.id_character
LEFT JOIN on_yomi ON character.id = on_yomi.id_character
LEFT JOIN kun_yomi ON kun_yomi.id_character = character.id 
LEFT JOIN meaning ON meaning.id_character = character.id 
WHERE character.id="]]..kanji..[[";
]]
end

function M.lookup_kanji(kanji)
    print("Opening " .. config.kanjidb)
    local con = sqlite3.open(config.kanjidb)
    local res = {}

    local req = kanji.kanji_sql(kanji)

    for a in con:nrows(req) do
        kanji.format_kanji(res)
        res [#res] = a
    end

    con:close()
    return res
end

return M

